local neogit = require('neogit')
vim.keymap.set('n', '<leader>g', function()
    neogit.open()
end)
vim.keymap.set('n', '<leader>gc', function()
    neogit.open({'commit'})
end)
vim.keymap.set('n', '<leader>gp', function()
    neogit.open({'push'})
end)
